version: "3"
services:
    website:
        build: /home/deshaan/dockerlab
        ports:
            - "80:80"
        volumes:
            - /var/www/html/:/usr/share/nginx/html
            - nginx_logs:/var/log/nginx
        networks:
            site_net:
                ipv4_address: 10.0.0.2
networks:
    site_net:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/24
volumes:
    nginx_logs:
